version: "3"
services:
    #RabbitMQ service
    rabbitmq7b:
        image: rabbitmq:3-management
        container_name: rabbitmq7b
        ports:
            - 15678:15672

    # nginx producer        
    nginx-producer7b:
        build:
            context: ./dockerfiles/build/nginx
            args:
                user_name: rabbitmq
                user_id: 1000
                group_id: 1000
                app_name: producer

        image: nginx-producer
        container_name: ngnix-producer7b
        ports:
            - "112:80"
        volumes:
            - ./producer:/home/rabbitmq/producer
            - ./dockerfiles/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
        restart: always
        depends_on:
            - php-producer7b

    # nginx consumer        
    nginx-consumer7b:
        build:
            context: ./dockerfiles/build/nginx
            args:
                user_name: rabbitmq
                user_id: 1000
                group_id: 1000
                app_name: consumer

        image: nginx-consumer
        container_name: ngnix-consumer7b
        ports:
            - "113:80"
        volumes:
            - ./consumer:/home/rabbitmq/consumer
            - ./dockerfiles/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
        restart: always
        depends_on:
            - php-consumer7b

    #php producer service
    php-producer7b:
        build:
            context: ./dockerfiles/build/php-fpm
            args:
                user_name: rabbitmq
                user_id: 1000
                group_id: 1000
                app_name: producer
        image: php-producer
        container_name: php-producer7b
        restart: always
        volumes:
            - ./producer:/home/rabbitmq/producer
            - ./dockerfiles/conf/php-fpm/upload.ini:/usr/local/etc/php/conf.d/upload.ini

    #php consumer service
    php-consumer7b:
        build:
            context: ./dockerfiles/build/php-fpm
            args:
                user_name: rabbitmq
                user_id: 1000
                group_id: 1000
                app_name: consumer
        image: php-consumer
        container_name: php-consumer7b
        restart: always
        volumes:
            - ./consumer:/home/rabbitmq/consumer
            - ./dockerfiles/conf/php-fpm/upload.ini:/usr/local/etc/php/conf.d/upload.ini

