version: "3"
services:
    #RabbitMQ service
    rabbitmq3:
        image: rabbitmq:3-management
        container_name: rabbitmq3
        ports:
            - 15673:15672

    # nginx producer        
    nginx-producer3:
        build:
            context: ./dockerfiles/build/nginx
            args:
                user_name: rabbitmq
                user_id: 1000
                group_id: 1000
                app_name: producer

        image: nginx-producer
        container_name: ngnix-producer3
        ports:
            - "102:80"
        volumes:
            - ./producer:/home/rabbitmq/producer
            - ./dockerfiles/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
        restart: always
        depends_on:
            - php-producer3

    # nginx consumer        
    nginx-consumer3:
        build:
            context: ./dockerfiles/build/nginx
            args:
                user_name: rabbitmq
                user_id: 1000
                group_id: 1000
                app_name: consumer

        image: nginx-consumer
        container_name: ngnix-consumer3
        ports:
            - "103:80"
        volumes:
            - ./consumer:/home/rabbitmq/consumer
            - ./dockerfiles/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
        restart: always
        depends_on:
            - php-consumer3

    #php producer service
    php-producer3:
        build:
            context: ./dockerfiles/build/php-fpm
            args:
                user_name: rabbitmq
                user_id: 1000
                group_id: 1000
                app_name: producer
        image: php-producer
        container_name: php-producer3
        restart: always
        volumes:
            - ./producer:/home/rabbitmq/producer
            - ./dockerfiles/conf/php-fpm/upload.ini:/usr/local/etc/php/conf.d/upload.ini

    #php consumer service
    php-consumer3:
        build:
            context: ./dockerfiles/build/php-fpm
            args:
                user_name: rabbitmq
                user_id: 1000
                group_id: 1000
                app_name: consumer
        image: php-consumer
        container_name: php-consumer3
        restart: always
        volumes:
            - ./consumer:/home/rabbitmq/consumer
            - ./dockerfiles/conf/php-fpm/upload.ini:/usr/local/etc/php/conf.d/upload.ini

